# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: KF5011 Computer Networks and Control Systems
email: alun.moon@northumbria.ac.uk
description: > # this means to ignore newlines until "baseurl:"
   Development and material for the new module, due Spring 2018
baseurl: "/kf5011" # the subpath of your site, e.g. /blog
url: "http://hesabu.net" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: ""
#url: ""
twitter_username:
github_username:

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-octicons
collections:
    seminars:
        output: true
    lectures:
        output: false
