#!/bin/sh
# install atom with platformio and dependencies
# Alun  5/05/2017


# platform IO needs clang, it has quite a few dependencies
# so the  --yes just installs the lot
sudo  apt-get install --yes git git-man liberror-perl clang

# atom isn't in the debian archives yet
# download the deb file and install it
wget -c https://atom-installer.github.com/v1.16.0/atom-amd64.deb
sudo  dpkg -i atom-amd64.deb


# all the following do *NOT* need to be installed as root
# installing as root messes up the package management.
# packages are stored in the users home directory ~/.atom
# apm is atom's package manager, you can do the same from
# inside atom with the package tab in settings
apm install autocomplete-clang
apm install build
apm install busy
apm install busy-signal
apm install file-icons
apm install intentions
apm install language-ini
apm install linter
apm install linter-gcc
apm install linter-ui-default
apm install minimap
apm install platformio-ide
apm install platformio-ide-debugger
apm install platformio-ide-terminal
apm install tool-bar
